#! /bin/sh

# Delete compiled templates.
rm -rf /opt/mkfusion/templates/*

# If Apache is running
IS_APACHE2_RUNNING=`service apache2 status`

if [ "$IS_APACHE2_RUNNING" != 'Apache is NOT running.' ]; then
    # remove mods_available symlink
    rm -f /etc/apache2/mods-enabled/mkfusion.load
    rm -f /etc/apache2/mods-enabled/mkfusion.conf

    # Restart Apache
    service apache2 restart
fi

# Stop MKFusion
service mkfusion stop

if [ $1 != "upgrade" ]; then
    # Delete config database
    rm -f /opt/mkfusion/bin/mkfusion.db
fi

exit 0

