#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          mkfusion
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# X-Interactive:     true
# Short-Description: Start/stop mkfusion app server
### END INIT INFO
#
# mkfusion		This init.d script is used to start mkfusion.
#			It basically just calls /opt/mkfusion/bin/mkfusion.

. /lib/lsb/init-functions

MKFUSION="/opt/mkfusion/bin/mkfusion"

case $1 in
	start)
		log_daemon_msg "Starting application server" "mkfusion"
		if $MKFUSION start; then
                        log_end_msg 0
                else
                        log_end_msg 1
                fi
	;;
	stop)
		log_daemon_msg "Stopping application server" "mkfusion"
		if $MKFUSION stop; then
                        log_end_msg 0
                else
                        log_end_msg 1
                fi
	;;
	restart)
		$0 stop
		$0 start
	;;
	status)
		if ; then
			PID= 
		else
			PID= ""
		fi

		if [ -n "$PID" ]; then
			echo "MKFusion is running (pid $PID)."
			exit 0
		else
			echo "MKFusion is NOT running."
			exit 1
		fi
	;;
	*)
		log_success_msg "Usage: /etc/init.d/mkfusion {start|stop|restart|status}"
		exit 1
	;;
esac
