#! /bin/sh -e

# Delete compiled templates.
unlink /opt/mkfusion/templates/*

# If Apache is running
if [`/etc/init.d/apache2 status` != 'Apache is NOT running.']; then
    # remove mods_available symlink
    unlink /etc/apache2/mods-enabled/mkfusion.load
    unlink /etc/apache2/mods-enabled/mkfusion.conf

    # Restart Apache
    /etc/init.d/apache2 restart
fi

# Stop MKFusion
/etc/init.d/mkfusion stop

if [ $1 != "upgrade" ]; then
    # Delete config database
    unlink /opt/mkfusion/bin/mkfusion.db
fi

exit 0
