#! /bin/sh

# Is mkfusion running?
IS_MKFUSION_RUNNING=`service mkfusion status`
if [ "$IS_MKFUSION_RUNNING" != 'MKFusion is NOT running.' ]; then
    # Stop mkfusion
    service mkfusion stop
fi

# Remove mkfusion daemon
insserv -r mkfusion

# Delete compiled templates.
rm -rf /opt/mkfusion/templates/*

# Disable mkfusion module
a2dismod mkfusion

# Is Apache running
IS_APACHE2_RUNNING=`service apache2 status`
if [ "$IS_APACHE2_RUNNING" != 'Apache is NOT running.' ]; then
    # Restart Apache
    service apache2 restart
fi

if [ $1 != "upgrade" ]; then
    # Delete config database
    rm -f /opt/mkfusion/bin/mkfusion.db
fi

exit 0

