#!/bin/sh

# Start MKFusion
service mkfusion start

# Add index.cfm to dir.conf


# If Apache is running
IS_APACHE2_RUNNING=`service apache2 status`

if [ "$IS_APACHE2_RUNNING" != 'Apache is NOT running.' ]; then
    # Restart Apache2.2
    service apache2 restart
fi

return 0

